name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Set to the branch name you want to trigger the build

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile  # Path to your Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: pantigon/microsoft-graph-smtp-relay  # Replace with your Docker Hub username, repository, and tag

    - name: Sync README to Docker Hub
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: pantigon/microsoft-graph-smtp-relay
        readme-filepath: ./README.md
